name: Build AutoGPTQ Wheels CPU only

on: workflow_dispatch

jobs:
  build_sdist:
    if: ${{ github.repository_owner == 'PanQiWei' }}
    name: Build source distribution
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'v0.2.2-patch-fix'

      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade build setuptools wheel

      - name: Build Wheel
        run: |
          echo $(ls)
          python setup.py sdist

      - uses: actions/upload-artifact@v3
        with:
          name: 'sdist'
          path: ./dist/*.tar.gz

#      - uses: actions/upload-artifact@v3
#        with:
#          name: 'no-cuda-wheel'
#          path: ./dist/*.whl
