name: check_code_quality

on:
  push:
    branches: [ main ]
    paths:
      - "auto_gptq/**.py"
      - "tests/**.py"
      - "examples/**.py"
      - "setup.py"

  pull_request:
    branches: [ main ]
    paths:
      - "auto_gptq/**.py"
      - "tests/**.py"
      - "examples/**.py"
      - "setup.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create and start a virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install torch
        echo "torch version:"
        python -c "import torch; print(torch.__version__);"
        echo "pip version:"
        pip --version
        which pip
        echo "python version:"
        python --version
        which python
        echo "setuptools version:"
        pip list | grep setuptools
        DISABLE_QIGEN=1 pip install -vvv .[quality]
    - name: Check style with ruff
      run: |
        source venv/bin/activate
        ruff .
